In [ ]:
# Web Scraping from Multiple Pages Website Campus.

In [12]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time 

time.sleep(5) 

URL = 'https://www.campusshoes.com/collections/men-sandals-floaters' 

HEADERS = { 'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36',
            'Accept-Language':'en-US, en;q=0.5' } 

response = requests.get(URL, headers=HEADERS)

info = BeautifulSoup(response.content, 'html.parser') 

product_description = [] 
product_MRP = [] 
product_curr_price = [] 
product_colour = [] 

while True:
    
    temp = info.find_all('h4', class_='p-title') 

    for val in temp:

        product_description.append(val.text.strip()) 
    
    temp = info.find_all('div', class_='product-price') 

    for val in temp:
        
        try:
    
            data = val.find('span', class_='product-price__item product-price__compare theme-money').text.strip() 

        except Exception: 

            data = 'N/A' 
    
        product_MRP.append(data)
    
    temp = info.find_all('div', class_='product-price')  
    
    for val in temp:
        
        try:
    
            data = val.find('span', class_='product-price__item product-price__amount product-price__amount--on-sale theme-money').text.strip()

        except Exception: 

            data = val.find('span', class_='product-price__item product-price__amount theme-money').text.strip()

        product_curr_price.append(data) 
    
    try:
    
        link = info.find('a', class_='next').get('href')

        URL = 'https://www.campusshoes.com' + link 
        
        HEADERS = { 'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36',
                    'Accept-Language':'en-US, en;q=0.5' } 

        response = requests.get(URL, headers=HEADERS) 

        info = BeautifulSoup(response.content, 'html.parser')
    
    except Exception:
        
        break 

DataFrame = pd.DataFrame({'FOOTWEAR_DESCRIPTION':product_description, 'FOOTWEAR_MRP':product_MRP, 'FOOTWEAR_CURRENT_PRICE':product_curr_price})

DataFrame

                  FOOTWEAR_DESCRIPTION FOOTWEAR_MRP FOOTWEAR_CURRENT_PRICE
0            GC-4003 Black Men's Clogs   Rs. 899.00             Rs. 814.00
1        GC-4003 Off White Men's Clogs   Rs. 899.00             Rs. 814.00
2          2GC-01 Men's Outdoor Sandal   Rs. 799.00             Rs. 649.00
3    2GC-16 Black Men's Outdoor Sandal   Rs. 699.00             Rs. 519.00
4            GC-4003 Olive Men's Clogs   Rs. 899.00             Rs. 814.00
..                                 ...          ...                    ...
258         GC-2306 Grey Men's Sandals   Rs. 999.00             Rs. 694.00
259         GC-2306 Grey Men's Sandals   Rs. 999.00             Rs. 694.00
260        GC-2306 Black Men's Sandals   Rs. 999.00             Rs. 694.00
261         SD-064 Beige Men's Sandals   Rs. 799.00             Rs. 599.00
262          3K-901 Blue Men's Sandals   Rs. 899.00             Rs. 624.00

[263 rows x 3 columns]

In [13]:
DataFrame.to_csv(r'C:\Users\rohit\OneDrive\Desktop\DataSets\Created_Datasets\Campus_Footwear_DataSet.csv', index=False)